apiVersion: apps/v1
kind: Deployment
metadata:
  name: cst-rakuten-frontend
  namespace: rakuten
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cst-rakuten-frontend
  template:
    metadata:
      labels:
        app: cst-rakuten-frontend
    spec:
      containers:
        - name: cst-rakuten-frontend-container
          image: ghcr.io/oondemand/cst-rakuten-segeti:${IMAGE_TAG}-homolog
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
            limits:
              memory: "4096Mi"
              cpu: "4"
